#!/bin/bash

# 🚀 ATHRO FEDERATION - Stripe Environment Setup Script
# This script configures Stripe environment variables for both frontend and backend

set -e

echo "🔧 Setting up Stripe environment variables..."

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Check if Supabase CLI is installed
if ! command -v supabase &> /dev/null; then
    echo -e "${RED}❌ Supabase CLI is not installed${NC}"
    echo -e "${YELLOW}Please install it first:${NC}"
    echo "brew install supabase/tap/supabase"
    echo "# or"
    echo "npx supabase@latest --help"
    exit 1
fi

echo -e "${GREEN}✅ Supabase CLI found${NC}"

# Prompt for Stripe credentials
echo ""
echo -e "${BLUE}🔑 Please provide your Stripe credentials:${NC}"

read -p "Stripe Secret Key (sk_test_... or sk_live_...): " STRIPE_SECRET_KEY
read -p "Stripe Webhook Secret (whsec_...): " STRIPE_WEBHOOK_SECRET
read -p "Stripe Lite Price ID (price_...): " STRIPE_LITE_PRICE_ID
read -p "Stripe Premium Price ID (price_...): " STRIPE_PREMIUM_PRICE_ID
read -p "Stripe Publishable Key (pk_test_... or pk_live_...): " STRIPE_PUBLISHABLE_KEY

# Validate inputs
if [[ -z "$STRIPE_SECRET_KEY" || -z "$STRIPE_WEBHOOK_SECRET" || -z "$STRIPE_LITE_PRICE_ID" || -z "$STRIPE_PREMIUM_PRICE_ID" || -z "$STRIPE_PUBLISHABLE_KEY" ]]; then
    echo -e "${RED}❌ All Stripe credentials are required${NC}"
    exit 1
fi

echo ""
echo -e "${YELLOW}🔧 Configuring Supabase Edge Functions...${NC}"

# Set Supabase secrets (for Edge Functions)
echo "Setting STRIPE_SECRET_KEY..."
supabase secrets set STRIPE_SECRET_KEY="$STRIPE_SECRET_KEY"

echo "Setting STRIPE_WEBHOOK_SECRET..."
supabase secrets set STRIPE_WEBHOOK_SECRET="$STRIPE_WEBHOOK_SECRET"

echo "Setting STRIPE_LITE_PRICE_ID..."
supabase secrets set STRIPE_LITE_PRICE_ID="$STRIPE_LITE_PRICE_ID"

echo "Setting STRIPE_PREMIUM_PRICE_ID..."
supabase secrets set STRIPE_PREMIUM_PRICE_ID="$STRIPE_PREMIUM_PRICE_ID"

echo ""
echo -e "${YELLOW}📝 Creating local environment file...${NC}"

# Create/update .env.local for frontend
ENV_FILE="apps/athro-dashboard/.env.local"

cat > "$ENV_FILE" << EOF
# 🔧 ATHRO DASHBOARD - Local Development Environment
# Generated by setup-stripe-environment.sh on $(date)

# Supabase Configuration (keep your existing values)
# VITE_SUPABASE_URL=your-supabase-url
# VITE_SUPABASE_ANON_KEY=your-supabase-anon-key

# Stripe Configuration - Frontend
VITE_STRIPE_PUBLISHABLE_KEY=$STRIPE_PUBLISHABLE_KEY
VITE_STRIPE_LITE_PRICE_ID=$STRIPE_LITE_PRICE_ID
VITE_STRIPE_PREMIUM_PRICE_ID=$STRIPE_PREMIUM_PRICE_ID

# Application URLs (adjust for your setup)
VITE_APP_URL=http://localhost:5173
VITE_SUCCESS_URL=http://localhost:5173/upgrade-success
VITE_CANCEL_URL=http://localhost:5173/upgrade-cancelled

# Development Flags
VITE_ENABLE_PAYMENTS=true
EOF

echo -e "${GREEN}✅ Created $ENV_FILE${NC}"

echo ""
echo -e "${YELLOW}🚀 Deploying Edge Functions...${NC}"

# Deploy the functions to apply new environment variables
supabase functions deploy create-checkout-session
supabase functions deploy stripe-webhook

echo ""
echo -e "${GREEN}🎉 Setup Complete!${NC}"
echo ""
echo -e "${BLUE}📋 Summary:${NC}"
echo "✅ Supabase secrets configured for Edge Functions"
echo "✅ Local environment file created: $ENV_FILE"
echo "✅ Edge Functions deployed with new environment"
echo ""
echo -e "${YELLOW}⚠️  Next Steps:${NC}"
echo "1. Update your Supabase URL and ANON_KEY in $ENV_FILE"
echo "2. Configure your Stripe webhook endpoint in Stripe Dashboard:"
echo "   URL: https://YOUR_PROJECT_REF.supabase.co/functions/v1/stripe-webhook"
echo "   Events: checkout.session.completed, customer.subscription.*"
echo "3. Test your payment flow"
echo ""
echo -e "${BLUE}🔗 Useful Commands:${NC}"
echo "supabase secrets list                    # View current secrets"
echo "supabase functions list                  # View deployed functions"
echo "supabase logs --project-ref YOUR_REF     # View function logs" 